export * from './school-address-form.component';
export * from './school-address.component';
export * from './school-contact-form.component';
export * from './school-contact.component';
export * from './school-details.component';
export * from './school-info-form.component';
export * from './school-info.component';
export * from './school-login-info.component';
export * from './school-person-form.component';
